config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :uploads, :only => [:new, :create, :show, :index, :edit, :destroy]

  match 'uploads/:id/download' => 'uploads#download', :as => :download, via: [:get]

  devise_scope :user do
    root to: "devise/registrations#new"
  end

end

app/models/upload.rb
class Upload < ActiveRecord::Base
  belongs_to :user

  has_attached_file :file
  # attr_accessor :file
  #
  validates :file, :attachment_presence => true
  do_not_validate_attachment_file_type :file
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :uploads
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  after_filter :store_location

  def store_location
    # store last url - this is needed for post-login redirect to whatever the user last visited.
    return unless request.get?
    if (request.path != "/users/sign_in" &&
        request.path != "/users/sign_up" &&
        request.path != "/users/password/new" &&
        request.path != "/users/password/edit" &&
        request.path != "/users/confirmation" &&
        request.path != "/users/sign_out" &&
        !request.xhr?) # don't store ajax calls
      session[:previous_url] = request.fullpath
    end
  end

  def after_sign_in_path_for(resource)
    uploads_path
  end

  # def after_sign_in_path_for(resource)
  #   uploads_path
  # end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

  def check_authorized
    if current_user != Upload.find(params[:id]).user

      flash[:notice] = "No such file found or Authorization Error"
      redirect_to action: "index" and return
    end
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :set_upload, only: [:show, :edit, :update, :destroy]

  before_action :check_authorized, only: [:show, :destroy, :download]

  before_action :authenticate_user!


  # GET /uploads
  # GET /uploads.json
  def index
    @uploads = current_user.uploads.all
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
    @upload = current_user.uploads.find(params[:id])
  end

  # GET /uploads/new
  def new
    @upload = Upload.new
  end

  # GET /uploads/1/edit
  def edit
  end

  # POST /uploads
  # POST /uploads.json
  def create

    unless upload_params
      redirect_to action: "index" and return
      return
    end

    @upload = current_user.uploads.new(upload_params)

    respond_to do |format|
      if @upload.save
        format.html { redirect_to @upload, notice: 'Rapid file uploaded successfully !!' }
        format.json { render :show, status: :created, location: @upload }
      else
        format.html { render :new }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uploads/1
  # PATCH/PUT /uploads/1.json
  def update
    # respond_to do |format|
    #   if @upload.update(upload_params)
    #     format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @upload }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @upload.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @upload.destroy
    respond_to do |format|
      format.html { redirect_to uploads_url, notice: 'Upload was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # def download
  #   @upload = Upload.find(params[:id])
  #   send_file @upload.path, type: @upload.content_type, disposition: 'attachment'
  # end

  def download
    puts "andalksdnalskdnlasdlaskd----------"
    @upload= Upload.find(params[:id])

    send_file @upload.file.path,
              :filename => @upload.file_file_name,
              :type => @upload.file_content_type,
              :disposition => 'attachment'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upload
      @upload = Upload.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def upload_params
      params.require(:upload).permit(:file)
      # render plain: "test"
      # return
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
  # def login_user
  #   before(:each) do
  #     @request.env["devise.mapping"] = Devise.mappings[:user]
  #     user = FactoryGirl.create(:user)
  #     user.confirm! # or set a confirmed_at inside the factory. Only necessary if you are using the "confirmable" module
  #     sign_in user
  #   end
  # end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RapidShareGem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <!---->
      <a class="navbar-brand" href="#">Rapid.sh</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%=  current_user.email%> <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="/uploads/">Rapid Files</a></li>
                <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete%></li>
              </ul>
            </li>
          </ul>
      <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> </li>
            <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
          </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

  <!--<p class="navbar-text pull-right">-->




  <% if notice %>
      <p class="alert alert-success text-center"><%= notice %></p>
  <% end %>
  <% if alert %>
      <p class="alert alert-danger text-center"><%= alert %></p>
  <% end %>

  <!--</p>-->

  <div class="jumbotron">
    <!--<h1>Navbar example</h1>-->
    <%= yield %>
    <!--<p>This example is a quick exercise to illustrate how the default, static navbar and fixed to top navbar work. It includes the responsive CSS and HTML, so it also adapts to your viewport and device.</p>-->

  </div>

  </div>



</body>
</html>

app/views/uploads/_form.html.erb
<%= form_for @upload, html: { multipart: true } do |f| %>
  <% if @upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
      <% @upload.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="  field">
    <%= f.file_field :file %>
  </div>
    <br/>
  <div class="actions">
    <%= f.submit "Upload", :class=>"btn btn-primary"%>
  </div>
<% end %>

app/views/uploads/edit.html.erb
<h1>Editing upload</h1>

<%= render 'form' %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>

app/views/uploads/index.html.erb
<center><h2>Rapid Uploads</h2></center>
<br/>
<table class="table">
  <thead>
    <tr>
      <th>File</th>
      <th>File Type</th>
      <th>Show</th>
      <!--<th>Edit</th>-->
      <th>Download</th>
      <th>Destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @uploads.each do |upload| %>
      <tr>
        <td><%= upload.file_file_name %></td>
        <td><%= upload.file_content_type %></td>
        <td><%= link_to 'Show', upload%></td>
        <!--<td><%= link_to 'Edit', edit_upload_path(upload) %></td>-->
        <td><%= link_to 'Download', download_path(upload) %></td>
        <td><%= link_to 'Destroy', upload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Upload', new_upload_path, :class=>"btn btn-lg btn-primary" %>

app/views/uploads/new.html.erb
<center>

<h3>Rapid File Upload</h3>
<br/>
<%= render 'form' %>
<br/>
<%= link_to 'Back', uploads_path %>
  <center>

app/views/uploads/show.html.erb
<!--<p>-->
  <!--<strong>File:</strong>-->

  <!--&lt;!&ndash;@galleries.each do |gallery|&ndash;&gt;-->
  <!--&lt;!&ndash;= link_to 'Download Picture', download_path(gallery.id)&ndash;&gt;-->
  <!--<%= @upload.file %>-->
  <!--<%= link_to "Download", download_path(@upload.id) %>-->

<!--</p>-->

<table class="table">
  <tr>
    <td><strong>File name:</strong></td>
    <td><%= @upload.file_file_name %></td>
  </tr>

  <tr>
    <td><strong>Size:</strong></td>
    <td><%= @upload.file_file_size %></td>
  </tr>

  <tr>
    <td><strong>Content-type:</strong></td>
    <td><%= @upload.file_content_type %></td>
  </tr>

  <tr>
    <td><strong>Download Link:</strong></td>
    <td><%= link_to "Download", download_path(@upload) %></td>
  </tr>

  <tr>
    <td><strong>Delete Link:</strong></td>
    <td><%= link_to 'Destroy', upload_path(@upload), :method => 'delete' %></td>
  </tr>
</table>

<!--<%= link_to 'Edit', edit_upload_path(@upload), :class=>"btn btn-primary"  %>-->
<%= link_to 'Back', uploads_path, :class=>"btn btn-primary"  %>